<?php
/**
 * Uninstall script for SEO Challenge Blueprint
 */

// If uninstall not called from WordPress, then exit
if (!defined('WP_UNINSTALL_PLUGIN')) {
    exit;
}

// Delete plugin options
delete_option('scb_settings');
delete_option('scb_version');
delete_option('scb_db_version');

// Remove scheduled events
wp_clear_scheduled_hook('scb_generate_content');

// Drop plugin tables
global $wpdb;

$tables = array(
    $wpdb->prefix . 'scb_agents',
    $wpdb->prefix . 'scb_topic_usage',
    $wpdb->prefix . 'scb_generated_content'
);

foreach ($tables as $table) {
    $wpdb->query("DROP TABLE IF EXISTS $table");
}

// Delete any posts generated by the plugin (optional - you might want to keep content)
$generated_posts = get_posts(array(
    'post_type' => 'post',
    'meta_key' => 'scb_generated',
    'meta_value' => true,
    'post_status' => 'any',
    'numberposts' => -1
));

foreach ($generated_posts as $post) {
    wp_delete_post($post->ID, true); // true = force delete, bypass trash
}

// Clear any cached data
wp_cache_flush();